### ISSUE TITLE
Add REQUIRE file to repository

### ISSUE THREAD

**Issue by hiccup7** [JuliaLang/Yeppp.jl#1]
Really cool package!  I am not clear if it is compatible with both Julia v0.3 and v0.4.  A REQUIRE file would clarify this.

Does the use of `Uint` arguments to ccall() imply that Yeppp.jl is incompatible with Julia v0.4?  If so, maybe need to use Compat.jl.

Also, are the `Int32` arguments to ccall() compatible with a 64-bit OS, where 64-bit integers are used in Julia?

Any plans to incorporate Yeppp.jl into the base to improve Julia's speed on vector math?

**Comment by ViralBShah** [comment]
I haven't given thought to all these important considerations yet. A PR is welcome. :-)

I have been using it with both 0.3 and 0.4. I think the Int32 arguments are what the Yeppp API has, so we are ok on that. I am using Yeppp on a 64-bit OS.

Unlikely that it will get incorporated in Base, since it has a relatively complex build process, and we will only get good implementations of half a dozen functions at best.

If this is popular, what we will do is address most of the issues discussed here, as well as make it easy to get the binaries via BinDeps.

**Comment by ViralBShah** [comment]
The way to get this in Base is to write these algorithms in pure Julia, which will require some compiler work as well.
